### PR TITLE
remove node sass as it is deprecated and a duplicate.

### PR DESCRIPTION
**Pull request by martincoote**
Sources
Outline of the problem here. https://developersociety.slack.com/archives/CGAPG8DC7/p1615568858026400

Description
Removing `node-sass` its not needed and was being used over the more up to date `dart-sass` (simply `sass` in package.json).

### CODE REVIEW

**Review by tomkins — CHANGES_REQUESTED** [review]
Could you remove it from package-lock.json?

Should be an easy chunk to remove!

**Comment by martincoote** [comment]
> Could you remove it from package-lock.json?
> 
> Should be an easy chunk to remove!

i can, i am reticent about manually editing package-lock though. maybe i should run it and copy over the package-lock that gets created.

Though do we even need a commited package-lock file in django template even?

**Comment by tomkins** [comment]
It should be safe and quick, it's what npm would do anyway. 😉 

We have package-lock.json so the template is reproducible. If depdencies drift and a bug occurs in a newer version, we waste time figuring it out.

This has actually happened before to Romek on a particular project.

**Comment by martincoote** [comment]
> It should be safe and quick, it's what npm would do anyway. 😉
> 
> We have package-lock.json so the template is reproducible. If depdencies drift and a bug occurs in a newer version, we waste time figuring it out.
> 
> This has actually happened before to Romek on a particular project.

okay i'll cut it out 🔪

**Review by tomkins — APPROVED** [review]

**Pull request merged**
